services:
    postgres:
        image: postgres:15-alpine
        container_name: meu-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: meu-app-node
        restart: unless-stopped
        env_file:
            - .env
        environment:
            NODE_ENV: development
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        ports:
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - .:/app
            - meu-projeto-node-modules:/app/node_modules
            - ./dados:/app/dados
        command: npm run dev
        networks:
            - app-network

volumes:
    postgres_data:
        name: meu-projeto-postgres-data
        driver: local

    meu-projeto-node-modules:
        name: meu-projeto-node-modules
        driver: local

networks:
    app-network:
        driver: bridge
